### ISSUE TITLE
ionic run android failed

### ISSUE THREAD

**Issue by Chilldev** [jdnichollsc/Ionic-Starter-Template#9]
after doing the following:
npm install, gulp
ionic run  android
Error: No platforms added to this project. Please use `cordova platform add <platform>`.
cordova platform add android
[cordova platform add android.txt](https://github.com/jdnichollsc/Ionic-Starter-Template/files/323089/cordova.platform.add.android.txt)

and finally ionic run android or cordova build android after adding the platform
[ionic run android.txt](https://github.com/jdnichollsc/Ionic-Starter-Template/files/323092/ionic.run.android.txt)

i'd really appreciate it if you could help

**Comment by jdnichollsc** [comment]
Execute the following commands:

cordova platform remove android
cordova platform add android
cordova prepare
ionic resources
ionic run android

Regards

**Comment by Chilldev** [comment]
works like a charm, thank you (A).

**Comment by dehamzah** [comment]
I also running into this problem, 
not also on android, it should run into problem too when building to ios.

The main cause is because the resources icon path generated in [`config.xml`](https://github.com/jdnichollsc/Ionic-Starter-Template/blob/master/config.xml#L29-L76),
the path generated there is windows style path, and maybe @Chilldev environment is linux / mac os.
So there the problem arise, because path in windows is `\` and linux or mac os is `/`.

The solution is just generate the new resources path:
```
$ ionic resources android
```
or
```
$ ionic resources ios
```

Then you can run on android or ios,
and maybe we should add this on readme so that people that running on linux / mac os environment didn't face this problem again.

**Comment by jdnichollsc** [comment]
@dehamzah Pull requests are welcome! 🥇
